import { Mails } from "lucide-react";
import { FC } from "react";

export const Footer: FC = () => {
  return (
    <div className="text-center flex flex-col items-center text-xs text-zinc-700 gap-1">
      <div className="text-zinc-400">
        Answer generated by large language models, plz double check for
        correctness.
      </div>
      <div className="flex gap-2 justify-center">
        <div>
          <a
            className="text-blue-500 font-medium inline-flex gap-1 items-center flex-nowrap text-nowrap"
            href="https://lepton.ai/"
          >
            <Mails size={8} />
            Lepton AI Website
          </a>
        </div>
        <div>if you need a performant and scalable AI cloud!</div>
      </div>

      
    </div>
  );
};
