import { LocaleType } from "./index";

const en: LocaleType = {
  Err: {
    429: "Sorry, you have made too many requests recently, try again later.",
    500: "Sorry, we might be overloaded, try again later.",
  },
  Title: {
    home: "Home",
  },
  Search: {
    placeholder: "Ask me anything ...",
  },
  Footer: {
    statement:
      "Answer generated by large language models, plz double check for correctness.",
  },
  Relates: {
    no_related_questions: "No related questions.",
    related: "Related",
  },
  Answer: {
    answer: "Answer",
  },
  Sources: {
    sources: "Sources",
  },
};

export default en;
