name: Docker Image CI

# push pr 的时候触发工作流
# on:
#   push:
#     branches: [ "docker-deploy-add-arm64-and-tags" ] # 测试分支 正式启用改为 main 下同
#     tags: [ "*" ]  # 监听所有标签推送事件
#   pull_request:
#     branches: [ "docker-deploy-add-arm64-and-tags" ]

# 只有在发布的时候才会触发工作流
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ secrets.DOCKERHUB_USERNAME }}/search4all
        tags: |
          type=raw,value=latest
          type=ref,event=tag
        
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha # 缓存加速编译
        cache-to: type=gha,mode=max
              